/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.ikitomo;

public class IkitomoMain {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new IkitomoMain().getGreeting());
    }
}
