/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.ikitomo;

import javafx.application.Application;

/**
 * A class which contains the main method
 */
public class IkitomoMain {
    /**
     * private constructor to prevent instantiation
     */
    private IkitomoMain() {
    }

    /**
     * main method
     * 
     * @param args the console args
     */
    public static void main(String[] args) {
        Application.launch(IkitomoApplication.class, args);
    }
}
