/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.ikitomo;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        IkitomoMain classUnderTest = new IkitomoMain();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
